name: Deploy DEV

on:
  pull_request:
    branches: [main]

jobs:
  testing-changes:
    runs-on: ubuntu-latest
    name: Build/Test
    steps:
      - uses: actions/checkout@v3

      - name: NPM - Install dependencies
        if: steps.cached-npm-dependencies.outputs.cache-hit != 'true'
        run: "npm install"

      - name: Run Tests
        run: |
          npm run test

  deploy-env:
    permissions:
      pull-requests: write
    name: Deploy Lambda
    runs-on: ubuntu-latest
    needs: testing-changes
    steps:
      - uses: actions/checkout@v3

      - name: NPM - Load cached venv
        id: cached-npm-dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: npm-${{ runner.os }}-${{ hashFiles('**/package.json') }}

      - name: NPM - Install dependencies
        if: steps.cached-npm-dependencies.outputs.cache-hit != 'true'
        run: "npm install"

      - name: Set Serverless Access Key
        run: echo "SERVERLESS_ACCESS_KEY=${{ secrets.SERVERLESS_ACCESS_KEY }}" >> $GITHUB_ENV

      - name: Deploy using sls
        run: "npx sls deploy"
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

      - name: Comment PR

        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            Your SLS App was deployed!
            Awesome :D
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
